# Generated by Django 3.1.7 on 2021-03-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_code', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('cost', models.IntegerField()),
                ('Rating', models.IntegerField()),
            ],
        ),
    ]
