# Generated by Django 3.1.7 on 2021-03-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hoteldata', '0002_delete_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SR_NO', models.IntegerField()),
                ('hotel_code', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('cost', models.IntegerField()),
                ('Rating', models.IntegerField()),
            ],
        ),
    ]
