# Generated by Django 3.1.7 on 2021-03-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteldata', '0003_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='Rating',
            field=models.FloatField(),
        ),
    ]
